### ISSUE TITLE
3 levels each game

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/OTTAAProject#36]
**Is your feature request related to a problem? Please describe.**
Yes, I need more levels based on user skills in the games. Sometimes when the users are playing is maybe to difficult or to easy for them. 

**Describe the solution you'd like**
I'd like to have 3 levels on each game, based on the user's skills. 

**Describe alternatives you've considered**
None

**Action Plan**

- [x] Design 3 levels for each game (Brainstorm)
- [x] Memory Game levels
- [x] Which is the Picto levels
- [x] Join Pictograms lelvels
- [x] Test each game
- [x] Implement instrumentation test

**Comment by gonojuarez** [comment]
on the which-is-the-picto game, the system changes the level game when the streak is 20.
the game has three levels
on the first level, the system shows two pictograms.
on the second level, the system shows three pictograms.
and in the last level, the system shows six pictograms

on the memory game or join pictograms game, the system changes the level game when the streak is 50.
the game has three levels
on the first level, the system shows six pictograms.
on the second level, the system shows eight pictograms.
and in the last level, the system shows ten pictograms

**Comment by gonojuarez** [comment]
In order to show when the system changes the game level, it is necessary to show the dialog at the moment

**Comment by hectoritr** [comment]
all done
