### ISSUE TITLE
Avatar recommendations

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/OTTAAProject#37]
**Is your feature request related to a problem? Please describe.**
No, but I want some recommendations based on usage given by my avatar. The avatar should be my "soul" inside the application. Should always give me data in a 3 person plural manner. 

**Describe the solution you'd like**
 Would be nice if the avatar encourages me to keep using the app and shows me some insights or data of my usage. The avatar should appear on the screen and by clicking it gives me recommendations, suggest me things to do, or to try. 

**Action Plan**

- [x] List all the possible suggestions
- [x] Evaluate if should be a Remote Config
- [x] Implement floating avatar
- [x] Make Custom toast use the Avatar
- [x] The avatar could be changed by the user
- [ ] Show avatar in the user report
- [ ] Implement 10 avatar actions.

**Comment by hectoritr** [comment]
Possible recommendations
- If the user touch multiple times in a short period of time should tell the user to wait
- When the user creates 10x sentences should say congratulations
- When the user reaches the "Agregar Picto" two times, suggest using the "Suggested Pictos"
- Suggest playing games
- When the user creates 3 times the same sentence suggest using Favorites pictos
- When the user deletes many times, suggest keeping pressed to delete all.

**Comment by hectoritr** [comment]
We are going to leave some communication to be sent through Remote config, such as important changes or events we are doing. Some others will be coded inside the application.
