### ISSUE TITLE
Automated Testing

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/OTTAAProject#38]
**Is your feature request related to a problem? Please describe.**
We need to implement instrumentation and UI testing to Circle CI pipeline

**Action Plan**

- [ ] Update RoboTest
- [ ] Implement instrumentation test in Firebase
- [ ] Implement UI testing in Firebase or TestProject
- [ ] Connect TestProject with Circle CI
- [ ] Share results in a visual way (e.g. a README badge)?
