### ISSUE TITLE
Favorite/Most Used Phrases Activity

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/OTTAAProject#58]
**Is your feature request related to a problem? Please describe.**
When a user has a lot of sentences and wants to add a sentence to the most used dialog, has to search one by one and it quite annoying. 

**Describe the solution you'd like**
Add a Searchview to filter by word

**Action Plan**

- [x] Migrate dialog to activity
- [x] Add SearchView to the Sentence picker
- [x] Filter the sentences per word.
- [x] Show only the sentences with that word.
- [x] Add Screen Scanning function
- [ ] Create Unit Testing
